"""empty message

Revision ID: 59440327c08a
Revises: a9eb77c3fe30
Create Date: 2025-05-07 19:45:07.525434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59440327c08a'
down_revision = 'a9eb77c3fe30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
